### ISSUE TITLE
Synk job fails for ion-store

### ISSUE THREAD

**Issue by ahoffer** [connexta/ion-cicd#12]
The Synk job fails in Circle CI workflow. The Circle workflow is defined this PR (https://github.com/connexta/ion-store/pull/170). 

This is the link to the workflow that failed: https://circleci.com/workflow-run/e602023c-3cb4-4bce-ad26-3058db560e35

The person working this issue can fork the ion-store repo and open a new PR against ion-store master. I suggest copying the files https://github.com/connexta/ion-store/pull/170/files as a starting point.

**Comment by j-fontaine** [comment]
Snyk is presently not outlined in the template file for gradle (which is the build engine used by connexta/ion-store).  I'm closing this as an issue at present and attempting to determine a better place to track this.
