### ISSUE TITLE
Quality scan fails for ion-store

### ISSUE THREAD

**Issue by ahoffer** [connexta/ion-cicd#13]
The quality scan job fails in Circle CI workflow. The Circle workflow is defined this PR (connexta/ion-store#170).

This is the link to the workflow that failed: https://circleci.com/workflow-run/e602023c-3cb4-4bce-ad26-3058db560e35

See also issue #12.

**Comment by j-fontaine** [comment]
Snyk is presently not outlined in the template file for gradle (which is the build engine used by connexta/ion-store).  I'm closing this as an issue at present and attempting to determine a better place to track this.

**Comment by j-fontaine** [comment]
Can you please outline what "quality scan" you are referencing?
Can you also please outline what functionality you expect would constitute "working"?  At present, my expectation would be that a properly configured SonarCloud scan would push results up to the Cloud UI for review and nothing more (no build breaker)

Assuming the above is correct, I don't think this is necessarily an issue with the template; but would prefer that we open this ticket against the connexta/ion-store implementation of the pipeline that isn't working and only open an issue here if we identify there is a stop gap in the pipeline templates.
